version: '3.8'

services:
    mongodb_playground:
        build:
            context: .
            dockerfile: Dockerfile
            volumes:
                -../..:/workspaces:cached
            network_mode: service:db
            command: sleep infinity

    db:
        image: mongo:4.4
        restart: unless-stopped
        ports:
        - "27017:27017"
        volumes:
        - mongodb-data:/data/db
volumes:
    mongodb-data: